[profile.default]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
src = "src"
out = "out"
libs = ["lib"]
ffi = false
bytecode_hash = "none"   # helps Etherscan verification
cbor_metadata = false
remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/"
]

[rpc_endpoints]
# Mainnets
ethereum = "${MAINNET_RPC_URL}"
base = "${BASE_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
bsc = "${BSC_RPC_URL}"
avalanche = "${AVAX_RPC_URL}"

# Testnets
sepolia = "${SEPOLIA_RPC_URL}"
base-sepolia = "${BASE_SEPOLIA_RPC_URL}"
arbitrum-sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
op-sepolia = "${OP_SEPOLIA_RPC_URL}"
amoy = "${POLYGON_AMOY_RPC_URL}"
bsc-testnet = "${BSC_TESTNET_RPC_URL}"
fuji = "${AVAX_FUJI_RPC_URL}"

[etherscan]
# Put your scanner API keys via envvars in .env
ethereum = { key = "${ETHERSCAN_API_KEY}" }
sepolia  = { key = "${ETHERSCAN_API_KEY}" }

base = { key = "${BASESCAN_API_KEY}" }
base-sepolia = { key = "${BASESCAN_API_KEY}" }

arbitrum = { key = "${ARBISCAN_API_KEY}" }
arbitrum-sepolia = { key = "${ARBISCAN_API_KEY}" }

optimism = { key = "${OPTIMISTIC_API_KEY}" }
op-sepolia = { key = "${OPTIMISTIC_API_KEY}" }

polygon = { key = "${POLYGONSCAN_API_KEY}" }
amoy = { key = "${POLYGONSCAN_API_KEY}" }

bsc = { key = "${BSCSCAN_API_KEY}" }
"bsc-testnet" = { key = "${BSCSCAN_API_KEY}" }

avalanche = { key = "${SNOWTRACE_API_KEY}" }
fuji = { key = "${SNOWTRACE_API_KEY}" }

[profile.sepolia-dev]
out = "out-sepolia-dev"
broadcast = "broadcast-sepolia-dev"
cache_path = "cache-sepolia-dev"

[profile.sepolia-prod]
out = "out-sepolia-prod"
broadcast = "broadcast-sepolia-prod"
cache_path = "cache-sepolia-prod"

[profile.mainnet]
out = "out-mainnet"
broadcast = "broadcast-mainnet"
cache_path = "cache-mainnet"